session_name: train
windows:
- window_name: train
  layout: tiled
  shell_command_before:
    - cd ~/pnml_ood/src
    - source ~/.bashrc
  panes:
    - shell_command:
      - CUDA_VISIBLE_DEVICES=0 python main_train.py -dataset cifar10 -model resnet
      - sleep 5s
      - CUDA_VISIBLE_DEVICES=0 python main_train.py -dataset cifar100 -model resnet
      - sleep 5s
      - CUDA_VISIBLE_DEVICES=0 python main_train.py -dataset cifar10 -model densenet
      - sleep 5s
      - CUDA_VISIBLE_DEVICES=0 python main_train.py -dataset cifar100 -model densenet