session_name: train_model
windows:
- window_name: train_model
  layout: tiled
  shell_command_before:
    - cd ~/pnml_ood/src
    - source ~/.bashrc
  panes:
    - shell_command:
      - CUDA_VISIBLE_DEVICES=0 python main_train.py -dataset_name cifar10 -model_name resnet
      - sleep 5s
      - CUDA_VISIBLE_DEVICES=0 python main_train.py -dataset_name cifar100 -model_name resnet
      - sleep 5s
      - CUDA_VISIBLE_DEVICES=0 python main_train.py -dataset_name cifar10 -model_name densenet
      - sleep 5s
      - CUDA_VISIBLE_DEVICES=0 python main_train.py -dataset_name cifar100 -model_name densenet