Gaussian:
    epsilon: 0
    temperature: 10
Imagenet:
    epsilon: 0.001
    temperature: 10
Imagenet_resize:
    epsilon: 0.0005
    temperature: 10
LSUN:
    epsilon: 0.0005
    temperature: 10
LSUN_resize:
    epsilon: 0.0005
    temperature: 10
Uniform:
    epsilon: 0
    temperature: 10
cifar10:
    epsilon: 0
    temperature: 1
iSUN:
    epsilon: 0.0005
    temperature: 10
svhn:
    epsilon: 0
    temperature: 10