Gaussian:
    epsilon: 0.0005
    temperature: 10
Imagenet:
    epsilon: 0.002
    temperature: 100
Imagenet_resize:
    epsilon: 0.002
    temperature: 100
LSUN:
    epsilon: 0.0014
    temperature: 1000
LSUN_resize:
    epsilon: 0.002
    temperature: 100
Uniform:
    epsilon: 0.0005
    temperature: 10
cifar10:
    epsilon: 0.0014
    temperature: 1000
cifar100:
    epsilon: 0.002
    temperature: 100
iSUN:
    epsilon: 0.002
    temperature: 100