Gaussian:
    epsilon: 0
    temperature: 1
Imagenet:
    epsilon: 0.001
    temperature: 10
Imagenet_resize:
    epsilon: 0.0014
    temperature: 10
LSUN:
    epsilon: 0
    temperature: 10
LSUN_resize:
    epsilon: 0.001
    temperature: 10
Uniform:
    epsilon: 0
    temperature: 1
cifar100:
    epsilon: 0
    temperature: 1
iSUN:
    epsilon: 0.001
    temperature: 10
svhn:
    epsilon: 0.01
    temperature: 100