Gaussian:
    epsilon: 0.0024
    temperature: 10
Imagenet:
    epsilon: 0.0014
    temperature: 10
Imagenet_resize:
    epsilon: 0.0014
    temperature: 10
LSUN:
    epsilon: 0
    temperature: 10
LSUN_resize:
    epsilon: 0.002
    temperature: 10
Uniform:
    epsilon: 0.002
    temperature: 10
cifar10:
    epsilon: 0.0014
    temperature: 10
cifar100:
    epsilon: 0.0014
    temperature: 100
iSUN:
    epsilon: 0.0014
    temperature: 100