Gaussian:
    epsilon: 0.0005
    temperature: 1
Imagenet:
    epsilon: 0.0005
    temperature: 10
Imagenet_resize:
    epsilon: 0.0014
    temperature: 1000
LSUN:
    epsilon: 0
    temperature: 10
LSUN_resize:
    epsilon: 0.002
    temperature: 100
Uniform:
    epsilon: 0.0005
    temperature: 1
cifar100:
    epsilon: 0.0005
    temperature: 10
iSUN:
    epsilon: 0.0014
    temperature: 100
svhn:
    epsilon: 0.005
    temperature: 1