Gaussian:
    epsilon: 0.002
    temperature: 1
Imagenet:
    epsilon: 0.0005
    temperature: 1
Imagenet_resize:
    epsilon: 0.0005
    temperature: 1
LSUN:
    epsilon: 0.0005
    temperature: 1
LSUN_resize:
    epsilon: 0.0005
    temperature: 1
Uniform:
    epsilon: 0.0014
    temperature: 1
cifar10:
    epsilon: 0.0005
    temperature: 1
cifar100:
    epsilon: 0.0005
    temperature: 1
iSUN:
    epsilon: 0.0005
    temperature: 1