Gaussian:
    epsilon: 0.0014
    temperature: 1
Imagenet:
    epsilon: 0
    temperature: 10
Imagenet_resize:
    epsilon: 0.001
    temperature: 1
LSUN:
    epsilon: 0
    temperature: 10
LSUN_resize:
    epsilon: 0.0014
    temperature: 1
Uniform:
    epsilon: 0.0014
    temperature: 1
cifar10:
    epsilon: 0
    temperature: 10
cifar100:
    epsilon: 0
    temperature: 100
iSUN:
    epsilon: 0
    temperature: 10