Gaussian:
    epsilon: 0.0024
    temperature: 1000
Imagenet:
    epsilon: 0.0024
    temperature: 100
Imagenet_resize:
    epsilon: 0.0024
    temperature: 100
LSUN:
    epsilon: 0.005
    temperature: 10
LSUN_resize:
    epsilon: 0.002
    temperature: 1000
Uniform:
    epsilon: 0.0024
    temperature: 100
cifar10:
    epsilon: 0
    temperature: 10
iSUN:
    epsilon: 0.0024
    temperature: 1000
svhn:
    epsilon: 0.01
    temperature: 10