# Project structure
data_dir: ../data       # The directory that contains the datasets
model_dir: ../models    # The directory that contains the trained model file

# Inference params
model: densenet         # Model architecture name (densenet/resnet)
trainset: cifar10       # Trainset that used to train the model (cifar10/cifar100/svhn)
batch_size: 256         # Batch size to use in the forward loop
num_workers: 4          # Number of CPU workers

num_skip_samples: 1000  # Number of samples that ODIN was optimized on. Skip in eval.

# Flow
test_pretrained: false
dev_run: false

# Odin perturbations
odin:
    densenet_cifar10:
        Gaussian:
            epsilon: 0.0005
            temperature: 1
        Imagenet:
            epsilon: 0.0005
            temperature: 10
        Imagenet_resize:
            epsilon: 0.0014
            temperature: 1000
        LSUN:
            epsilon: 0
            temperature: 10
        LSUN_resize:
            epsilon: 0.002
            temperature: 100
        Uniform:
            epsilon: 0.0005
            temperature: 1
        cifar100:
            epsilon: 0.0005
            temperature: 10
        iSUN:
            epsilon: 0.0014
            temperature: 100
        svhn:
            epsilon: 0.005
            temperature: 1
    densenet_cifar100:
        Gaussian:
            epsilon: 0.0
            temperature: 1.0
        Imagenet:
            epsilon: 0.0024
            temperature: 10
        Imagenet_resize:
            epsilon: 0.0024
            temperature: 10
        LSUN:
            epsilon: 0.0024
            temperature: 10
        LSUN_resize:
            epsilon: 0.0024
            temperature: 10
        Uniform:
            epsilon: 0.0024
            temperature: 1
        cifar10:
            epsilon: 0.0014
            temperature: 10
        iSUN:
            epsilon: 0.0024
            temperature: 10
        svhn:
            epsilon: 0.005
            temperature: 1
    densenet_svhn:
        Gaussian:
            epsilon: 0.002
            temperature: 1
        Imagenet:
            epsilon: 0.0005
            temperature: 1
        Imagenet_resize:
            epsilon: 0.0005
            temperature: 1
        LSUN:
            epsilon: 0.0005
            temperature: 1
        LSUN_resize:
            epsilon: 0.0005
            temperature: 1
        Uniform:
            epsilon: 0.0014
            temperature: 1
        cifar10:
            epsilon: 0.0005
            temperature: 1
        cifar100:
            epsilon: 0.0005
            temperature: 1
        iSUN:
            epsilon: 0.0005
            temperature: 1
    resnet_cifar10:
        Gaussian:
            epsilon: 0.0005
            temperature: 1
        Imagenet:
            epsilon: 0.0014
            temperature: 10
        Imagenet_resize:
            epsilon: 0.0014
            temperature: 10
        LSUN:
            epsilon: 0.001
            temperature: 1000
        LSUN_resize:
            epsilon: 0.0014
            temperature: 100
        Uniform:
            epsilon: 0.001
            temperature: 1
        cifar100:
            epsilon: 0.0005
            temperature: 1000
        iSUN:
            epsilon: 0.0014
            temperature: 100
        svhn:
            epsilon: 0.01
            temperature: 1
    resnet_cifar100:
        Gaussian:
            epsilon: 0.0024
            temperature: 1000
        Imagenet:
            epsilon: 0.0024
            temperature: 100
        Imagenet_resize:
            epsilon: 0.0024
            temperature: 100
        LSUN:
            epsilon: 0.005
            temperature: 10
        LSUN_resize:
            epsilon: 0.002
            temperature: 1000
        Uniform:
            epsilon: 0.0024
            temperature: 100
        cifar10:
            epsilon: 0
            temperature: 10
        iSUN:
            epsilon: 0.0024
            temperature: 1000
        svhn:
            epsilon: 0.01
            temperature: 10
    resnet_svhn:
        Gaussian:
            epsilon: 0.0014
            temperature: 1
        Imagenet:
            epsilon: 0
            temperature: 10
        Imagenet_resize:
            epsilon: 0.001
            temperature: 1
        LSUN:
            epsilon: 0
            temperature: 10
        LSUN_resize:
            epsilon: 0.0014
            temperature: 1
        Uniform:
            epsilon: 0.0014
            temperature: 1
        cifar10:
            epsilon: 0
            temperature: 10
        cifar100:
            epsilon: 0
            temperature: 100
        iSUN:
            epsilon: 0
            temperature: 10

# Odin+pNML perturbations
odin_pnml:
    densenet_cifar10:
        Gaussian:
            epsilon: 0
            temperature: 1
        Imagenet:
            epsilon: 0.001
            temperature: 10
        Imagenet_resize:
            epsilon: 0.0014
            temperature: 10
        LSUN:
            epsilon: 0
            temperature: 10
        LSUN_resize:
            epsilon: 0.001
            temperature: 10
        Uniform:
            epsilon: 0
            temperature: 1
        cifar100:
            epsilon: 0
            temperature: 1
        iSUN:
            epsilon: 0.001
            temperature: 10
        svhn:
            epsilon: 0.01
            temperature: 100
    densenet_cifar100:
        Gaussian:
            epsilon: 0
            temperature: 10
        Imagenet:
            epsilon: 0.001
            temperature: 10
        Imagenet_resize:
            epsilon: 0.0005
            temperature: 10
        LSUN:
            epsilon: 0.0005
            temperature: 10
        LSUN_resize:
            epsilon: 0.0005
            temperature: 10
        Uniform:
            epsilon: 0
            temperature: 10
        cifar10:
            epsilon: 0
            temperature: 1
        iSUN:
            epsilon: 0.0005
            temperature: 10
        svhn:
            epsilon: 0
            temperature: 10
    densenet_svhn:
        Gaussian:
            epsilon: 0.0005
            temperature: 10
        Imagenet:
            epsilon: 0.002
            temperature: 100
        Imagenet_resize:
            epsilon: 0.002
            temperature: 100
        LSUN:
            epsilon: 0.0014
            temperature: 1000
        LSUN_resize:
            epsilon: 0.002
            temperature: 100
        Uniform:
            epsilon: 0.0005
            temperature: 10
        cifar10:
            epsilon: 0.0014
            temperature: 1000
        cifar100:
            epsilon: 0.002
            temperature: 100
        iSUN:
            epsilon: 0.002
            temperature: 100
    resnet_cifar10:
        Gaussian:
            epsilon: 0
            temperature: 1
        Imagenet:
            epsilon: 0.0014
            temperature: 10
        Imagenet_resize:
            epsilon: 0.0014
            temperature: 10
        LSUN:
            epsilon: 0.002
            temperature: 10
        LSUN_resize:
            epsilon: 0.0014
            temperature: 10
        Uniform:
            epsilon: 0.001
            temperature: 1
        cifar100:
            epsilon: 0.0005
            temperature: 1000
        iSUN:
            epsilon: 0.002
            temperature: 10
        svhn:
            epsilon: 0.01
            temperature: 10
    resnet_cifar100:
        Gaussian:
            epsilon: 0.0024
            temperature: 10
        Imagenet:
            epsilon: 0.0024
            temperature: 1000
        Imagenet_resize:
            epsilon: 0.0024
            temperature: 100
        LSUN:
            epsilon: 0.005
            temperature: 100
        LSUN_resize:
            epsilon: 0.002
            temperature: 10
        Uniform:
            epsilon: 0.0024
            temperature: 10
        cifar10:
            epsilon: 0.001
            temperature: 10
        iSUN:
            epsilon: 0.002
            temperature: 1
        svhn:
            epsilon: 0.01
            temperature: 100
    resnet_svhn:
        Gaussian:
            epsilon: 0.0024
            temperature: 10
        Imagenet:
            epsilon: 0.0014
            temperature: 10
        Imagenet_resize:
            epsilon: 0.0014
            temperature: 10
        LSUN:
            epsilon: 0
            temperature: 10
        LSUN_resize:
            epsilon: 0.002
            temperature: 10
        Uniform:
            epsilon: 0.002
            temperature: 10
        cifar10:
            epsilon: 0.0014
            temperature: 10
        cifar100:
            epsilon: 0.0014
            temperature: 100
        iSUN:
            epsilon: 0.0014
            temperature: 100

hydra:
  run:
    dir: ../outputs/odin_${model}_${trainset}_${now:%Y%m%d_%H%M%S}