session_name: extract_odin
windows:
- window_name: extract_odin
  layout: even-vertical
  shell_command_before:
    - cd ../src/
    - source ~/.bashrc
    - conda activate ood
  panes:
    - shell_command:
      - sleep 0s
      - CUDA_VISIBLE_DEVICES=0 python main_extract.py --config-name=extract_odin model=densenet trainset=cifar10
    - shell_command:
      - sleep 5s
      - CUDA_VISIBLE_DEVICES=1 python main_extract.py --config-name=extract_odin model=densenet trainset=cifar100
    - shell_command:
      - sleep 10s
      - CUDA_VISIBLE_DEVICES=2 python main_extract.py --config-name=extract_odin model=densenet trainset=svhn
    - shell_command:
      - sleep 15s
      - CUDA_VISIBLE_DEVICES=3 python main_extract.py --config-name=extract_odin model=resnet trainset=cifar10
    - shell_command:
      - sleep 20s
      - CUDA_VISIBLE_DEVICES=4 python main_extract.py --config-name=extract_odin model=resnet trainset=cifar100
    - shell_command:
      - sleep 25s
      - CUDA_VISIBLE_DEVICES=5 python main_extract.py --config-name=extract_odin model=resnet trainset=svhn
