session_name: optimize_odin
windows:
- window_name: optimize_odin
  layout: even-vertical
  shell_command_before:
    - cd ../src/
    - source ~/.bashrc
    - conda activate ood
  panes:
    - shell_command:
      - sleep 0s
      - CUDA_VISIBLE_DEVICES=0 python optimize_odin.py model=densenet trainset=cifar10
      - CUDA_VISIBLE_DEVICES=0 python optimize_odin.py model=densenet trainset=cifar10 is_with_pnml=true
    - shell_command:
      - sleep 5s
      - CUDA_VISIBLE_DEVICES=1 python optimize_odin.py model=densenet trainset=cifar100
      - CUDA_VISIBLE_DEVICES=1 python optimize_odin.py model=densenet trainset=cifar100 is_with_pnml=true
    - shell_command:
      - sleep 10s
      - CUDA_VISIBLE_DEVICES=2 python optimize_odin.py model=densenet trainset=svhn
      - CUDA_VISIBLE_DEVICES=2 python optimize_odin.py model=densenet trainset=svhn is_with_pnml=true
    - shell_command:
      - sleep 15s
      - CUDA_VISIBLE_DEVICES=3 python optimize_odin.py model=resnet trainset=cifar10
      - CUDA_VISIBLE_DEVICES=3 python optimize_odin.py model=resnet trainset=cifar10 is_with_pnml=true
    - shell_command:
      - sleep 20s
      - CUDA_VISIBLE_DEVICES=4 python optimize_odin.py model=resnet trainset=cifar100
      - CUDA_VISIBLE_DEVICES=4 python optimize_odin.py model=resnet trainset=cifar100 is_with_pnml=true
    - shell_command:
      - sleep 25s
      - CUDA_VISIBLE_DEVICES=5 python optimize_odin.py model=resnet trainset=svhn
      - CUDA_VISIBLE_DEVICES=5 python optimize_odin.py model=resnet trainset=svhn is_with_pnml=true